# src/models/enums.py
from enum import Enum

class TaskStatus(Enum):
    PENDING = "PENDING"
    BUFFERED = "BUFFERED"
    ASSIGNED = "ASSIGNED"
    COMPLETED = "COMPLETED"

class EventType(Enum):
    GENERATE_TASK = "GENERATE_TASK"
    TASK_ARRIVES_AT_DISPATCHER = "TASK_ARRIVES_AT_DISPATCHER"
    # TASK_ACCEPTED_BY_WAREHOUSE = "TASK_ACCEPTED_BY_WAREHOUSE" # Убрано
    # TASK_REJECTED_BY_WAREHOUSE = "TASK_REJECTED_BY_WAREHOUSE" # Убрано
    TASK_ENTERED_BUFFER = "TASK_ENTERED_BUFFER"
    TASK_REPLACED_IN_BUFFER = "TASK_REPLACED_IN_BUFFER"
    TASK_PICKED_FROM_BUFFER = "TASK_PICKED_FROM_BUFFER"
    DEVICE_BECAME_FREE = "DEVICE_BECAME_FREE"
    TASK_ASSIGNED_TO_DEVICE = "TASK_ASSIGNED_TO_DEVICE"
    TASK_COMPLETED_BY_DEVICE = "TASK_COMPLETED_BY_DEVICE"